name: Amazon Competitors Tracker

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch: {}  # permite ejecución manual

permissions:
  contents: write

concurrency:
  group: amazon-competitors-tracker
  cancel-in-progress: false

jobs:
  discover-asins:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build matrix from Asins/*.txt
        id: build-matrix
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=(Asins/asins_*.txt)

          if [ ${#files[@]} -eq 0 ]; then
            echo "No se encontraron archivos Asins/asins_*.txt. La matriz quedará vacía y no habrá ejecuciones."
            echo 'matrix=[]' >> "$GITHUB_OUTPUT"
            exit 0
          fi

          # Construir un array JSON de objetos { "asin_file": "<path>" }
          json=$(printf '%s\n' "${files[@]}" | awk '{print "{\"asin_file\":\""$0"\"}"}' | jq -s .)
          echo "matrix=$json" >> "$GITHUB_OUTPUT"
          echo "Matriz detectada: $json"

  fetch-and-commit:
    needs: discover-asins
    if: ${{ needs.discover-asins.outputs.matrix != '[]' }}  # salta si no hay archivos
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      max-parallel: 1   # ejecutar de a uno
      matrix:
        include: ${{ fromJson(needs.discover-asins.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests pandas python-dotenv
          fi

      - name: Run data request for ${{ matrix.asin_file }}
        env:
          RAPIDAPI_KEY: ${{ secrets.AMAZON_API_KEY }}
          COUNTRY: US
          ASIN_FILE: ${{ matrix.asin_file }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Processing $ASIN_FILE ..."
          python request-api.py
          echo "Sleeping 1s to respect API pacing..."
          sleep 1

      - name: Get UTC timestamp
        id: ts
        shell: bash
        run: echo "utc=$(date -u +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_OUTPUT"

      - name: Commit y push automáticos
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update competitors CSVs (UTC ${{ steps.ts.outputs.utc }})"
          branch: main
